enum ExpressionKind {
	case Invalid;
	case Group;
	case Cast;
	case Sizeof;
	case Offsetof;
	case Dereference;
	case Reference;
	case FunctionCall;
	case Subscript;
	case Arrow;
	case Dot;
	case InfixOperator;
	case Identifier;
	case _NULL;
	case BooleanLiteral;
	case IntegerLiteral;
	case CharacterLiteral;
	case StringLiteral;
};
